const data = Object.freeze([1,2,3,4]);
/**
 * @param  {} val
 * @param  {} =>val.toString(
 * 
 * ! test comment
 * todo how 
 */
const addEmoji = (val) => val.toString()+"<3";

const emojiData = data.map(addEmoji);

console.log(emojiData);

// Generated by https://quicktype.io

export interface Account {
    id:                    number;
    name:                  string;
    balance:               number;
    currency:              Currency;
    currencyId:            number;
    userId:                number;
    isShared:              boolean;
    sharedWithId:          number;
    sharingConfirmedOther: boolean;
    dateCreated:           string;
    lastConfirmed:         string;
    userPriority:          number;
}

export interface Currency {
    id:           number;
    name:         string;
    priceInEur:   number;
    userId:       number;
    isShared:     number;
    userPriority: number;
}
